---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.background-name }}"
  labels:
    app: "{{ .Values.background-name }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.background-name }}"
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Values.background-name }}"
    spec:
      volumes:
      - name: api-config-volume
        configMap:
          name: api-config
      containers:
      - name: "{{ .Values.background-name }}"
        image: "{{ .Values.deployment.image }}:{{ .Values.deployment.tag }}"
        volumeMounts:
        - name: api-config-volume
          mountPath: /app/checker.txt
          subPath: checker.txt
        ports:
        - containerPort: 3000
          protocol: TCP
        {{- if .Values.deployment.resources }}
        resources:
          {{- if .Values.deployment.resources.requests }}
          requests:
            memory: {{ .Values.deployment.resources.requests.memory | default "50Mi" | quote }}
            cpu: {{ .Values.deployment.resources.requests.cpu | default "10m" | quote }}
          {{- else}}
          requests:
            memory: "50Mi"
            cpu: "10m"
          {{- end}}
          {{- if .Values.deployment.resources.limits }}
          limits:
            memory: {{ .Values.deployment.resources.limits.memory | default "1024Mi" | quote }}
            cpu: {{ .Values.deployment.resources.limits.cpu | default "1" | quote }}
          {{- else}}  
          limits:
            memory: "1024Mi"
            cpu: "1"
          {{- end }}
        {{- else }}
        resources:
          requests:
            memory: "50Mi"
            cpu: "10m"
          limits:
            memory: "1024Mi"
            cpu: "1"
        {{- end}} 