apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-bg-ingress
spec:
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: "{{ .Values.api-name }}"
            port:
              number: 80
      - path: /bg
        pathType: Prefix
        backend:
          service:
            name: "{{ .Values.bg-name }}"
            port:
              number: 80